(1,'Afghanistan','AFG'),
(2,'Alaska','ALK'),
(3,'Albania','ALB'),
(4,'Algeria','DZA'),
(5,'Angola','AGO'),
(6,'Argentina','ARG'),
(7,'Australia','AUS'),
(8,'Austria','AUT'),
(9,'Azerbaijan','AZE'),
(10,'Bahamas','BHS'),
(11,'Bahrain','BHR'),
(12,'Bangladesh','BGD'),
(13,'Barbados','BRB'),
(14,'Belarus','BLR'),
(15,'Belgium','BEL'),
(16,'Belize','BLZ'),
(17,'Benin','BEN'),
(18,'Bermuda','BMU'),
(19,'Botswana','BWA'),
(20,'Brazil','BRA'),
(21,'Bulgaria','BGR'),
(22,'Burkina Faso','BFA'),
(23,'Burundi','BDI'),
(24,'Cambodia','KHM'),
(25,'Cameroon','CMR'),
(26,'Canada','CAN'),
(27,'Canary Is.','CAN'),
(28,'Cape Verde Republic','CPV'),
(29,'Cayman Islands','CYM'),
(30,'Central African Republic','CAF'),
(31,'Chile','CHL'),
(32,'China','CHN'),
(33,'Colombia','COL'),
(34,'Comoros','COM'),
(35,'Congo','COG'),
(36,'Croatia','HRV'),
(37,'Cuba','CUB'),
(38,'Cyprus','CYP'),
(39,'Czech Republic','CZE'),
(40,'Denmark','DNK'),
(41,'Djibouti','DJI'),
(42,'Dominican Republic','DOM'),
(43,'Ecuador','ECU'),
(44,'Egypt','EGY'),
(45,'El Salvador','SLV'),
(46,'Ethiopia','ETH'),
(47,'Finland','FIN'),
(48,'France','FRA'),
(49,'Gabon','GAB'),
(50,'Gambia','GMB'),
(51,'Georgia','GEO'),
(52,'Germany','DEU'),
(53,'Ghana','GHA'),
(54,'Gibralter','GIB'),
(55,'Greece','GRC'),
(56,'Greenland','GRL'),
(57,'Guatemala','GTM'),
(58,'Guine-bissau','GNB'),
(59,'Guinee','GNQ'),
(60,'Guyana','GUY'),
(61,'Honduras','HND'),
(62,'Hungary','HUN'),
(63,'Iceland','ISL'),
(64,'India','IND'),
(65,'Indonesia','IDN'),
(66,'Iran','IRN'),
(67,'Iraq','IRQ'),
(68,'Ireland','IRL'),
(69,'Israel','ISR'),
(70,'Italy','ITA'),
(71,'Ivory Coast','CIV'),
(72,'Jamaica','JAM'),
(73,'Japan','JPN'),
(74,'Kenya','KEN'),
(75,'Latvia','LVA'),
(76,'Lesotho','LSO'),
(77,'Liberia','LBR'),
(78,'Libya','LBY'),
(79,'Lithuania','LTU'),
(80,'Luxembourg','LUX'),
(81,'Madagascar','MDG'),
(82,'Malawi','MWI'),
(83,'Malaysia And Brunei','MYS'),
(84,'Mali','MLI'),
(85,'Malta','MLT'),
(86,'Mauritania','MRT'),
(87,'Mauritius','MUS'),
(88,'Mexico','MEX'),
(89,'Morocco','MAR'),
(90,'Mozambique','MOZ'),
(91,'Nepal','NPL'),
(92,'Netherlands','NLD'),
(93,'New Zealand','NZL'),
(94,'Niger','NER'),
(95,'Nigeria','NGA'),
(96,'Norway','NOR'),
(97,'Oman','OMN'),
(98,'Pakistan','PAK'),
(99,'Papua New Guinea','PNG'),
(100,'Philippines','PHL'),
(101,'Poland','POL'),
(102,'Portugal','PRT'),
(103,'Puerto Rico','PRI'),
(104,'Qatar','QAT'),
(105,'Romania','ROU'),
(106,'Russia','RUS'),
(107,'Sao Tome And Principe','STP'),
(108,'Saudi Arabia','SAU'),
(109,'Senegal','SEN'),
(110,'Seychelles','SYC'),
(111,'Sierra Leone','SLE'),
(112,'Singapore','SGP'),
(113,'Slovak Republic','SVK'),
(114,'Slovenia','SVN'),
(115,'Somalia Republic','SOM'),
(116,'South Africa','ZAF'),
(117,'South Korea','PRK'),
(118,'Spain','ESP'),
(119,'Sri Lanka','LKA'),
(120,'Sudan','SDN'),
(121,'Swaziland','SWZ'),
(122,'Sweden','SWE'),
(123,'Switzerland','CHE'),
(124,'Syria','SYR'),
(125,'Taiwan','TWN'),
(126,'Tanzania','TZA'),
(127,'Tchad','TCD'),
(128,'Thailand','THA'),
(129,'Togo','TGO'),
(130,'Trinidad And Tobago','TTO'),
(131,'Tunisia','TUN'),
(132,'Turkey','TUR'),
(133,'Turkmenistan','TKM'),
(134,'Uganda','UGA'),
(135,'Ukraine','UKR'),
(136,'United Arab Emirates','ARE'),
(137,'United Kingdom','GBR'),
(138,'United States','USA'),
(139,'Uruguay','URY'),
(140,'Uzbekistan','UZB'),
(141,'Venezuela','VEN'),
(142,'Vietnam','VNM'),
(143,'Yemen','YEM'),
(144,'Yugoslavia','YUG'),
(145,'Zaire','ZAR'),
(146,'Zambia','ZMB'),
(147,'Zimbabwae','ZWE');
